# -*- mode: ruby -*-
# vi: set ft=ruby :

vm_hostname = "docktor-ci-manager"
vm_ip = "192.168.35.121"
vm_name = "Docktor CI/CD manager"
vm_user = "vagrant"
vm_hieradata_dir = "/etc/puppet/hieradata"
# vm_root_dir = "/var/www/#{vm_hostname}"
puppet_modulepath = "/etc/puppet/modules"
#puppet_modulepath = "/usr/share/puppet/modules" # can be set to /etc/puppet/modules
vm_bin = "/usr/local/bin"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu-14.04"
  config.vm.hostname = vm_hostname
  config.vm.boot_timeout = 720
  config.vm.box_check_update = true

  config.vm.network "private_network", ip: vm_ip

  # VMWare-specific settings
  config.vm.provider "vmware_fusion" do |v, override|
    #v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    v.vmx["displayname"] = vm_name

    # No need for NFS for VMWARE
    # override.vm.synced_folder "./", vm_root_dir
  end

  # Virtualbox-specific settings
  config.vm.provider "virtualbox" do |vb, override|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = "2"
    vb.name = vm_name

    # Ensure that project config via provisioner has the same root dir
    # override.vm.synced_folder "../", vm_root_dir, type: "nfs"
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true # disable syn to "/vagrant" folder

  #config.vm.synced_folder "../data/private/certs", "/certs", type: "rsync"

  config.vm.synced_folder "puppet/modules", puppet_modulepath
  config.vm.synced_folder "puppet", "/etc/puppet", type: "rsync", rsync__exclude: ["modules/"]

  # copy SSH keys to vagrant
  config.vm.synced_folder "~/.ssh", "/home/vagrant/.ssh_host", type: "rsync", rsync__exclude: ["authorized_keys"]

  # TODO: remove. Is temporary for development
  config.vm.synced_folder "../data", "/data"

  # copy binaries
  config.vm.synced_folder "../bin", vm_bin, type: "rsync"

  # init docker and setup environment
  config.vm.provision "shell", name: "Setup server configuration", path: "../bin/provision.sh"

  # puppet install
  config.vm.provision "puppet" do |puppet|
    puppet.synced_folder_type = "rsync"
    puppet.manifests_path = "puppet"
    puppet.manifest_file = "site.pp"
    puppet.options = "--yamldir #{vm_hieradata_dir}"
    puppet.hiera_config_path = "puppet/hiera.yaml"
    puppet.module_path = "puppet/modules"

    #puppet.working_directory = "/etc/puppet"
    #puppet.temp_dir = "/tmp/tmp-puppet"
    #puppet.working_directory = "/tmp/vagrant-puppet"
  end

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "zig-zag/docktor-ci-manager"
  # end

end
