name    'zigzag-ci_manager'
version '0.1.0'
source 'UNKNOWN'
author 'zig-zag'
license 'Apache License, Version 2.0'
summary 'CI/Projects Manager'
description 'Manager for Docktor servers family'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 4.9.0'
dependency 'garethr/docker', '>= 4.1.1'
dependency 'dockerui/dockerui', '>= 0.0.1'
